### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4,6
  description: Microsoft Application Virtualization 4,6 следует за фиксированной политикой жизненного цикла.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "835950"
name: Microsoft Application Virtualization 4,6
summary: >+
  Microsoft Application Virtualization 4,6 следует за [фиксированной](/lifecycle/policies/fixed) политикой жизненного цикла.


  Это относится к следующим выпускам: для служб удаленных рабочих столов — для настольных систем Windows, секвенсора

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Ссылки \n* [Сведения о продукте и миграции](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Руководство по миграции](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Политика пакетов обновления](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Так как клиент App — V 4,6 использует сервер App/v 4,5, сервер App + V 4,5 будет поддерживаться в соответствии с датами жизненного цикла App + V 4,6, когда используется с поддерживаемым клиентом App + V 4,6.\n\n## <a name=\"editions\"></a>2003 \n* для служб удаленных рабочих столов\n* для настольных компьютеров с Windows\n* Sequencer"
