### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security соответствует фиксированной политике жизненного цикла.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908880"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security соответствует [фиксированной](/lifecycle/policies/fixed) политике жизненного цикла.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Ссылки \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security больше не используется. Поддержка заканчивается в июле 14th 2015 г. Обновления определений защиты от вредоносных программ и антишпионского по не будут доступны после завершения поддержки версии продукта. Оцените защиту конечных точек System Center в качестве замены."
