### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows
  description: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows следует Фиксированной политике жизненного цикла.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows
summary: |+
  Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows следует [Фиксированной](/lifecycle/policies/fixed) политике жизненного цикла.

  Данное правило распространяется на следующие выпуски: для настольных компьютеров Windows

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Ссылки 
  * [Информация по миграции и продуктах](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Политика пакетов обновления](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Так как клиент App-V 4.6 использует сервер App-V 4.5, при использовании с поддерживаемым клиентом App-V 4.6 сервер App-V 4.5 будет продолжать поддерживаться в соответствии с датами жизненного цикла App-V 4.6.

  ## <a name="editions"></a>Выпуски 
  * для настольных компьютеров Windows