### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows
  description: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows следует Фиксированной политике жизненного цикла.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153937"
name: Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 для настольных компьютеров Windows следует [Фиксированной](/lifecycle/policies/fixed) политике жизненного цикла.


  Данное правило распространяется на следующие выпуски: для настольных компьютеров Windows

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ссылки \n* [Информация по миграции и продуктах](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Политика пакетов обновления](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Так как клиент App-V 4.6 использует сервер App-V 4.5, при использовании с поддерживаемым клиентом App-V 4.6 сервер App-V 4.5 будет продолжать поддерживаться в соответствии с датами жизненного цикла App-V 4.6.\n\n## <a name=\"editions\"></a>Выпуски \n* для настольных компьютеров Windows"
