### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization следует Политике фиксированного жизненного цикла.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "835246"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization следует Политике [фиксированного](/lifecycle/policies/fixed) жизненного цикла.


  Данное правило распространяется на следующие выпуски: 4.1 для рабочих столов, 4.2 для рабочих столов, для служб терминалов 4.1


  > [!IMPORTANT]

  > Поддержка закончилась. См. ниже руководство по миграции.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Ссылки \n* [Руководство по миграции](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Выпуски \n* 4.1 для рабочих столов\n* 4.2 для рабочих столов\n* для служб терминалов 4.1"
