### YamlMime:Lifecycle
metadata:
  title: Whale Communications Intelligent Application Gateway
  description: Whale Communications Intelligent Application Gateway следует фиксированной политике жизненного цикла Whale Communications.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: ru-RU
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907154"
name: Whale Communications Intelligent Application Gateway
summary: >+
  Whale Communications Intelligent Application Gateway следует [фиксированной политике](/lifecycle/policies/fixed) жизненного цикла Whale Communications.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Поддержка данного продукта предоставляется в соответствии с условиями, указанными при его приобретении."
